version: "3.9"
services:
  moviedb:
    image: postgres:alpine
    container_name: moviedb
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movie
    volumes:
      - storage:/deeeesp/moviedb
    networks:
      - db-back
  backend:
    container_name: backend
    restart: always
#    build:
#      context: .
    image: docker.io/deeeesp/movieserver:latest
    ports:
      - "8080:8080"
    depends_on:
      - moviedb
    networks:
      - db-back
    environment:
      - DB_URL=jdbc:postgresql://moviedb:5434/movie
      - DB_USER=postgres
      - DB_PASS=postgres

volumes:
  storage:

networks:
  db-back: